---
# General
storage_bucket_allowed_account_ids:
  - "%{hiera('bsn_development_potassium_account_id')}"

database_version: "4.4"
database_instance_size_name: "M10"
database_allow_cidrs:
  - "10.0.0.0/8"

database_username: "%{hiera('database_service_user_username')}"
database_password: "%{hiera('database_service_user_password')}"

database_type: "deployed"

# State
network_state_bucket_name: "bsn-application-network-bsn-development-palladium"
network_state_key: "network/deployment-state/default.tfstate"
network_state_bucket_region: "%{hiera('region')}"
network_state_bucket_is_encrypted: "true"

cluster_state_bucket_name: "bsn-application-cluster-bsn-development-tennessine"
cluster_state_key: "cluster/deployment-state/default.tfstate"
cluster_state_bucket_region: "%{hiera('region')}"
cluster_state_bucket_is_encrypted: "true"

database_state_bucket_name: "%{hiera('storage_bucket_name')}"
database_state_key: "database/deployment-state/default.tfstate"
database_state_bucket_region: "%{hiera('region')}"
database_state_bucket_is_encrypted: "true"
