---
# General
storage_bucket_allowed_account_ids:
  - "%{hiera('rdm_management_account_id')}"
  - "%{hiera('bsn_development_potassium_account_id')}"
  - "%{hiera('bsn_production_lutetium_account_id')}"

development_tennessine_cluster_instance_role_arn: "arn:aws:iam::384010198059:role/terraform-20210413135553345900000003"
production_gold_cluster_instance_role_arn: "arn:aws:iam::371854298993:role/terraform-20210413135959680100000003"

image_repository_allowed_role_arns:
  - "%{hiera('development_tennessine_cluster_instance_role_arn')}"
  - "%{hiera('production_gold_cluster_instance_role_arn')}"

database_version: "4.4"
database_instance_size_name: "M10"
database_allow_cidrs:
  - "10.0.0.0/8"

database_username: "%{hiera('database_service_user_username')}"
database_password: "%{hiera('database_service_user_password')}"

database_type: "deployed"

# State
network_state_bucket_name: "rdm-tooling-network-rdm-management-default"
network_state_key: "network/deployment-state/default.tfstate"
network_state_bucket_region: "%{hiera('region')}"
network_state_bucket_is_encrypted: "true"

database_state_bucket_name: "%{hiera('storage_bucket_name')}"
database_state_key: "database/deployment-state/default.tfstate"
database_state_bucket_region: "%{hiera('region')}"
database_state_bucket_is_encrypted: "true"

image_repository_state_bucket_name: "%{hiera('storage_bucket_name')}"
image_repository_state_key: "image-repository/deployment-state/default.tfstate"
image_repository_state_bucket_region: "%{hiera('region')}"
image_repository_state_bucket_is_encrypted: "true"

image_storage_bucket_state_bucket_name: "%{hiera('storage_bucket_name')}"
image_storage_bucket_state_key: "image-storage-bucket/deployment-state/default.tfstate"
image_storage_bucket_state_bucket_region: "%{hiera('region')}"
image_storage_bucket_state_bucket_is_encrypted: "true"
