---
# General
database_version: "4.4"
database_instance_size_name: "M10"
database_allow_cidrs:
  - "10.0.0.0/8"

# State
network_state_bucket_name: "rdm-tooling-network-rdm-management-default"
network_state_key: "network/deployment-state/default.tfstate"
network_state_bucket_region: "%{hiera('region')}"
network_state_bucket_is_encrypted: "true"

database_state_bucket_name: "%{hiera('storage_bucket_name')}"
database_state_key: "database/deployment-state/default.tfstate"
database_state_bucket_region: "%{hiera('region')}"
database_state_bucket_is_encrypted: "true"
