NETWORK_NAME="rinkeby"
EXECUTOR_PRIVATE_KEY="${executor_secret}"
GCLOUD_SECRET="${gcloud_keepers_secret}"
ALCHEMY_URL="${alchemy_url}"
ETHERSCAN_API_KEY="${etherscan_apikey}"
INFURA_API_KEY="${infura_apikey}"
API_URL="https://reference-backend-bsn-poc-sposite.bsn-development-potassium.bosonprotocol.io"
PROVIDER_URL="https://eth-desired-network.alchemyapi.io/v2/your-api-key"