---
:backends:
  - "overrides"
  - "env"
  - "yaml"
:logger: "noop"
:yaml:
  :datadir: "config"
:hierarchy:
  - "roles/%{role}"
  - "deployments/%{deployment_type}-%{deployment_label}"
  - "pipelines/defaults"
  - "ci/%{ci_deployment_type}-%{ci_deployment_label}"
  - "secrets/app/%{deployment_type}-%{deployment_label}"
  - "secrets/mongodbatlas/credentials"
  - "secrets/database/%{deployment_type}-%{deployment_label}"
  - "secrets/pipeline/%{ci_deployment_type}-%{ci_deployment_label}"
  - "defaults"
