---
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  mongodb_atlas_organization_id: "%{hiera('mongodb_atlas_organization_id')}"
  mongodb_atlas_public_key: "%{hiera('mongodb_atlas_public_key')}"
  mongodb_atlas_private_key: "%{hiera('mongodb_atlas_private_key')}"

  database_version: "%{hiera('database_version')}"
  database_instance_size_name: "%{hiera('database_instance_size_name')}"
  database_service_user_username: "%{hiera('database_service_user_username')}"
  database_service_user_password: "%{hiera('database_service_user_password')}"
  database_read_only_user_username: "%{hiera('database_read_only_user_username')}"
  database_read_only_user_password: "%{hiera('database_read_only_user_password')}"
  database_allow_cidrs: "%{hiera('database_allow_cidrs')}"

  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_key: "%{hiera('network_state_key')}"
  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"
  network_state_bucket_is_encrypted: "%{hiera('network_state_bucket_is_encrypted')}"

backend_config:
  bucket: "%{hiera('database_state_bucket_name')}"
  key: "%{hiera('database_state_key')}"
  region: "%{hiera('database_state_bucket_region')}"
  encrypt: "%{hiera('database_state_bucket_is_encrypted')}"
